<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RsvpCodesSeederNew extends Seeder
{
    public function run()
    {
        DB::table('rsvp_codes')->insert([
            [
                'code' => 'PWKA-5697',
                'invitee' => 'Kris and Shannon',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'JSIP-9015',
                'invitee' => 'Sam and Amanda',
                'user_id' => null,
                'expected_party_size' => 5,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'IPAX-0098',
                'invitee' => 'David and Shannon',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'YROP-0997',
                'invitee' => 'Gary and Joyce',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'YLNV-6338',
                'invitee' => 'Phil Bausch and Family',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'BXSO-8553',
                'invitee' => 'Ryan, Natalina, and Noah',
                'user_id' => null,
                'expected_party_size' => 3,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'VNIB-4011',
                'invitee' => 'John, Dianna, and Family',
                'user_id' => null,
                'expected_party_size' => 7,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'YJXX-9415',
                'invitee' => 'Cheyenne Robertson and Family',
                'user_id' => null,
                'expected_party_size' => 3,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'LITH-2157',
                'invitee' => 'Jim and Anita Braden',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'YYMP-4660',
                'invitee' => 'Leonard and Carol Chatfield',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'UYDZ-0111',
                'invitee' => 'Kevin Campbell',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'TRAJ-8073',
                'invitee' => 'Virgil and Judy Chapman',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'VZIJ-7074',
                'invitee' => 'Mike Hunnitcutt',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'SMZT-9774',
                'invitee' => 'Matt Hunnicutt',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'YOVI-4551',
                'invitee' => 'Melissa Galyean',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'MDJH-9285',
                'invitee' => 'Mindy Hunnicutt',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'ITTH-0547',
                'invitee' => 'Jeni Hunnicutt',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'BKLN-8646',
                'invitee' => 'John, Sarah, and Atlie',
                'user_id' => null,
                'expected_party_size' => 3,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'NXTE-0261',
                'invitee' => 'Joe, Hillary and Family',
                'user_id' => null,
                'expected_party_size' => 3,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'JSCX-6602',
                'invitee' => 'Jake, Allison and Family',
                'user_id' => null,
                'expected_party_size' => 5,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'TRKA-3862',
                'invitee' => 'Becky Hassler',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'UEOK-6113',
                'invitee' => 'Nathan, Amanda, and Family',
                'user_id' => null,
                'expected_party_size' => 3,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'AWSH-9277',
                'invitee' => 'Lettie Johnson',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'DCSZ-2141',
                'invitee' => 'Kathy Mannahan',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'RGWF-0183',
                'invitee' => 'Joan Mannahan and Family',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'TQCB-8216',
                'invitee' => 'Julie Mather',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'GNNG-5824',
                'invitee' => 'Danny Sanders',
                'user_id' => null,
                'expected_party_size' => 1,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'BYSP-0722',
                'invitee' => 'Luke, Sara, and Family',
                'user_id' => null,
                'expected_party_size' => 5,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'HMLK-6745',
                'invitee' => 'Eli Sanders and Family',
                'user_id' => null,
                'expected_party_size' => 5,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'BUQP-4288',
                'invitee' => 'Roger and Kay Smith',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'PQFP-5349',
                'invitee' => 'Mike and Lana Todd',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'SWWN-7331',
                'invitee' => 'Richard and Tressa Townsend',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
            [
                'code' => 'ECJW-7270',
                'invitee' => 'Lindy and Karen Woods',
                'user_id' => null,
                'expected_party_size' => 2,
                'actual_party_size' => null,
                'is_accepted' => false,
                'invited_to_both' => 1,
                'created_at' => now(),
            ],
        ]);
    }
}